import bangun_datar; from kalkulator import *
print("HASIL")
print("~~~~~~~~~~~~~~~~~~~~~~~~~~~~~")
bangun_datar.persegi(10)
print("~~~~~~~~~~~~~~~~~~~~~~~~~~~~~")
bangun_datar.segitiga(3,4,5,4)
print("~~~~~~~~~~~~~~~~~~~~~~~~~~~~~")
bangun_datar.persegipanjang(2,3)
print("~~~~~~~~~~~~~~~~~~~~~~~~~~~~~")
bangun_datar.belahketupat(3,2,2,5,4,5)
print("~~~~~~~~~~~~~~~~~~~~~~~~~~~~~")
bangun_datar.jajargenjang(2,4,3,6,4)
print("~~~~~~~~~~~~~~~~~~~~~~~~~~~~~")
bangun_datar.lingkaran(5)
print("~~~~~~~~~~~~~~~~~~~~~~~~~~~~~")
bangun_datar.trapesium(3,4,2,3,2)
print("^^^^^^^^^^^^^^^^^^^^")
print("Perhitungan Kalkulator")
print()
penjumlahan(2,2)
pengurangan(5,2)
perkalian(13,4)
pembagian(100,2)
pangkat(2,3)
akar(2)
log(2)
sin(5)
cos(10)
tan(50)

